import random

facts = [
    ["The novel coronavirus is named SARS-CoV-2 and the disease is COVID-19.","The virus is now named SARS-CoV-2, for Severe Acute Respiratory Syndrome-Coronavirus-2, because the virus is very similar to the SARS coronavirus first discovered in 2003. The SARS-CoV-2 disease is named COVID-19, for Coronavirus Disease 2019."],
    ["The 2019 coronavirus spreads easily from person to person.", "On January 30, 2020, the CDC confirmed the first person-to-person transmission of the new coronavirus. SARS-CoV-2 spreads through tiny respiratory droplets from the nose or mouth when an infected person coughs or sneezes. The droplets can make contact within 6 feet. You can contract the coronavirus if these droplets land in your nose or mouth, you inhale them, or you touch a contaminated surface or object and then touch your nose or mouth before washing your hands. Infected people are contagious with or without symptoms. Studies show the virus multiplies fast in the nose and throat, even in the beginning of an infection when the person does not yet feel ill. Approximately 25% of infected individuals may not develop symptoms, but are still capable of spreading the virus."],
    ["The first cases in the United States were mainly in people who traveled from China.", "Some of the first known cases of COVID-19 in the United States were in people returning from travel abroad, from China, cruise ships, and subsequently from other countries with COVID-19 spread. These are so-called “imported” cases. On February 25, 2020, the CDC diagnosed the new coronavirus disease in a person who lives in California but who had no known travel history or close contact with an infected person. Doctors consider these \"community\" cases because they did not arise from a known source."],
    ["COVID-19 is widespread in the United States.", "The coronavirus is spreading at different rates in different parts of the country. The CDC says the risk to the general public of contracting the virus is still considered low in areas without community spread. However, SARS-CoV-2 is a highly contagious virus and outbreaks are still occurring."],
    ["Social distancing helps slow the spread of infection.", "Since January and early February, the CDC has been warning the country to prepare for a pandemic, but to not panic. Keep in mind the term “pandemic” speaks to the geographical reach of the virus, and not the severity of the disease. Do your part to slow the spread of COVID-19 by 'social distancing,' which is avoiding large public gatherings, wearing a cloth mask over your mouth and nose, and keeping a distance of at least 6 feet from other people. 'Stay at home,' or 'shelter at home' policies to slow the spread of the new coronavirus are working. They are also giving healthcare providers and hospitals more time to treat people who are sick."],
    ["COVID-19 symptoms range from mild to severe, and it can be fatal.", "The common cold is also spread by a coronavirus (as well as other types of viruses). For some patients, coronavirus symptoms mimic those of a common cold, while others experience the same symptoms that accompany a severe respiratory infection. COVID-19 symptoms include fever, cough, body aches, sore throat, fatigue, phlegm/sputum production, and shortness of breath. An unexpected symptom of COVID-19 is loss of sense of smell. In some cases, the virus attacks the lungs and symptoms are severe enough the patient requires hospital care with supplemental oxygen and fluids, even breathing support with a ventilator. COVID-19 symptoms can appear within 2 to 14 days after exposure. Of the more than 1.5 million confirmed U.S. COVID-19 cases, 361,528 have recovered so far. The current U.S. mortality rate is 5.8%. The first U.S. death due to COVID-19 was reported in February 2020; 93,708 deaths have since been reported. The COVID-19 mortality rate may be much lower considering the potential number of undiagnosed cases. The risk of dying from COVID-19 is greater in people who have underlying chronic health conditions, such as heart, lung or liver disease."],
    ["Treatment options are limited to addressing the symptoms.", "There is no specific drug for COVID-19, but the Food and Drug Administration recently approved the antiviral drug, remdesivir for emergency use in COVID-19 patients. It is authorized for use in adults and children with a blood oxygen saturation level of ≤ 94% and who require supplemental oxygen, mechanical ventilation, or extracorporeal membrane oxygenation (a type of life support). The drug can speed up recovery time in severely ill patients.\n Research and development continues on finding a more targeted treatment and many drugs are in clinical trials. In the meantime, hospitalized patients receive appropriate treatment for serious respiratory symptoms. Doctors are giving some patients plasma donated from recovered COVID-19 patients, to help the patient fight the infection. \nIf a person with COVID-19 does not require medical care, they should stay home, self-quarantine from others in the household, and restrict any activity outside the home to prevent transmission."],
    ["There is no vaccine for 2019-nCoV (SARS-CoV-2) infection.", "Because there currently is no vaccine to protect against the novel coronavirus, the best prevention against the virus is to avoid exposure. To help prevent and slow the spread of this and other viruses, wash your hands often using soap and water for at least 20 seconds. Alcohol-based hand sanitizer can be used when soap and water are not available. Avoid close contact with anyone, especially people who are showing signs of a respiratory infection, and keep washing your hands. If you are sick, stay home and isolate yourself from others in the household. \nScientists are currently testing potential vaccines against the novel coronavirus (SARS-CoV-2), and one is expected to be available in early 2021."],
    ["The source of the novel coronavirus is linked to animals.", "Because many patients in the Wuhan, China outbreak were linked to a large seafood and animal market, the 2019 coronavirus was thought the virus spread directly from animals to humans. However, once in humans, the virus was able to spread person to person. This is similar to the spread of two other coronaviruses that originated from animals: SARS-CoV (civet cats) and MERS-CoV (camels). There are many different coronaviruses. They mainly infect animals, but some of the viruses can spread from animals to humans. This is the case with SARS-CoV, MERS-CoV, and the new coronavirus (SARS-CoV-2): All three viruses came from bats originally."],
    ["Speak to your doctor about getting tested for COVID-19.", "If you have symptoms of COVID-19, contact your doctor about getting tested for the virus. Currently, healthcare providers, other frontline workers, and people at risk for severe COVID-19 have testing priority over the general public. If you do not have COVID-19 symptoms, but you have either been in close contact with someone who has COVID-19 or you or a close contact has been in an area with community transmission, you may be a candidate for testing if you fall within one of the priority groups. COVID-19 testing criteria vary by area. \nIf you returned from any country or area with sustained transmission of COVID-19, follow CDC guidelines. This will likely include self- or mandatory quarantine. With a self-quarantine, you must stay home and avoid in-person contact for 14 days, while monitoring yourself for signs and symptoms of COVID-19.  If you develop symptoms call your healthcare provider if develop serious symptoms, including difficulty breathing. Your doctor may decide to test you if other causes are ruled out. \nIf you do not meet the testing criteria but you have mild cold symptoms, such as a cough or sore throat, stay home. Avoid calling your healthcare provider, urgent care, or emergency department unless you have serious symptoms, such as trouble breathing. If you have a cough and fever, call your doctor in case it is the flu. As always, if you require emergency medical attention, call 911. Tell the dispatcher of any possible exposure to coronavirus and all symptoms you are experiencing. If your health insurance plan offers telemedicine, consider using it. \nFor the most recent information about COVID-19, check the CDC website for updates, including the number of confirmed cases and advice for travelers. Call your state's public health department for local information. Some states have set up phone hotlines. "],
]

def random_facts():
    i = random.randrange(0, len(facts))
    return facts[i]
